storacha/ucanto

.gitignore
Readme.md
package.json
packages/authority/package.json
packages/client/package.json
packages/client/test/services/account.js
packages/core/package.json
packages/interface/package.json
packages/interface/src/capability.ts
packages/interface/src/lib.ts
packages/server/package.json
packages/server/src/api.ts
packages/server/src/handler.js
packages/server/src/lib.js
packages/server/src/server.js
packages/server/test/service/access.js
packages/transport/package.json
packages/validator/package.json
packages/validator/src/capability.js
packages/validator/src/lib.js

1. Removes prepare scripts since git deps don't work on monorepos anyway.
2. Adds .env to .gitignore
3. Improves handling of optional caveats on capabilities.
4. Improves `provide` to support derived capabilities.
5. Updates some tests to map uploads-v2 better.

feat: cherry pick changes from uploads-v2 demo

---

packages/client/src/lib.js
packages/core/src/invocation.js
packages/core/src/lib.js
packages/core/test/invocation.spec.js
packages/interface/src/capability.ts
packages/interface/src/lib.ts
packages/interface/src/query.ts
packages/server/src/handler.js
packages/server/src/lib.js
packages/validator/package.json
packages/validator/src/capability.js
packages/validator/src/decoder/uri.js
packages/validator/src/error.js
packages/validator/src/lib.js
packages/validator/test/capability.spec.js
packages/validator/test/decoder.spec.js
packages/validator/test/lib.spec.js
packages/validator/tsconfig.json

This PR adds following features:
1. `derives` is now optional in `capability({ ... })`. If not provided will use a default which:
1. Verifies that `claimed.with` is same as `delegated.with` or that `claimed.with` is inside `delegated.with` if later ends with `*`.
2. Verifies that all the `delegated.caveats` are same on `claimed.caveats`.
In many instances you'd need to define custom `derives`, but I think sane default is probably a good idea.
2. Capabilities defined with `capability()` now have `.create({ with: resource, caveats: { ... } })` function  which:
1. Will create capability object with desired `can` field.
2. Will pass inputs through decoders to avoid creating ones that will fail to parse on the other end.
3. Will throw error if parameters are invalid.
3. Capabilities defined …

feat(ucanto): capability create / inovke methods

---

.github/workflows/release.yml
packages/client/src/connection.js
packages/client/test/client.spec.js
packages/interface/src/lib.ts
packages/server/test/handler.spec.js
packages/server/test/server.spec.js
packages/transport/src/car/codec.js
packages/transport/test/car.spec.js

- client now needs DID of the service (you really need both everywhere and it makes sense to just stick one there)
- car encoder now exports `link` function for case where you just want to generate CAR cid from car bytes.

upstream changes from w3 branch

---

pnpm-lock.yaml
w3/sigv4/package.json
w3/sigv4/test/sigv4.test.js

Addresses failures observed in https://github.com/web3-storage/ucanto/pull/62
I believe whatever "assert" module was loaded in chrome did not have assert.match function which caused test fail.

fix: use chai assert

---

.github/workflows/interface.yml
w3/sigv4/src/index.js
w3/sigv4/src/types.ts
w3/store/src/signer/lib.js
w3/store/src/signer/type.ts

Extends options for the signer service and the SIGV4 to allow passing the security token generated when a temp IAM is used instead of a user based one.

W3 signer token

---

packages/transport/src/http.js
packages/transport/test/https.spec.js

```
TypeError: 'fetch' called on an object that does not implement interface Window.
```

fix: default fetch implementation called on non Window object

---

packages/server/src/server.js

Destructuring like `{ catch: fail }` causes TS to generate invalid typedfes

fix(server): generarting invaild typedefs

---

Readme.md

Hey @Gozala I was checking out the README and figured I'd make a couple grammar edits along the way.
Also, I noticed in the batching & proofs example that you're saving the delegation result to a `proof` variable, but it's not being used anywhere... does it need to be used in the invocations somehow?

chore: grammar / spelling edits in README

---

package.json
packages/client/package.json
packages/core/package.json
packages/interface/package.json
packages/interface/src/capability.ts
packages/principal/package.json
packages/server/package.json
packages/transport/package.json
packages/validator/package.json
packages/validator/src/capability.js
packages/validator/test/capability.spec.js
packages/validator/test/delegate.spec.js
packages/validator/test/inference.spec.js
packages/validator/test/lib.spec.js
packages/validator/test/util.js
packages/validator/test/voucher.js
pnpm-lock.yaml

Fixes #123 
---
I hate introducing more utility types to make this work, but unfortunately there was no simple way to fix all the problems. It is possible to rework validator such that we would be able to remove bunch of these utility types, however it is non trivial change and I'd rather do it later on when there's less urgency.

fix: optional field validation

---

packages/interface/src/lib.ts

I started reading a bit deeper into ucanto as I'm thinking about ways to document the capability and service definitions.
I added some doc comments to some of the types in the main `interface` package, mostly to try to clarify my understanding. I haven't got to the more gnarly inference / capability parsing stuff yet and may leave that stuff for later. Mostly just want to cover types that you might encounter if you're defining a ucanto service implementation.
@Gozala could you look through and see if I'm describing things correctly?

chore: add doc comments to interface/lib.ts

---

packages/validator/test/delegate.spec.js

I have been seeing these kind of failures every now and then https://github.com/web3-storage/ucanto/actions/runs/3605142474/jobs/6075233040. Turns out some tests just compare delegations which may end up different because expiry date is encoded in UCANs, so if wall clock second mark changes between calls we get a different expiry. In tests it may happens because of the await in between.
This pr changes all tests to use fixed expiry to make them clock agnostic

fix: intermittent test fails

---

packages/core/package.json
packages/core/test/delegation.spec.js
packages/interface/package.json
packages/interface/src/lib.ts
packages/principal/package.json
pnpm-lock.yaml

Propagates changes form https://github.com/ipld/js-dag-ucan/pull/72 into ucanto and adds some tests to ensure no regressions
Supersedes #173

fix: toJSON behavior on the ucan.data

---

packages/validator/src/schema/schema.js
packages/validator/src/schema/type.ts
packages/validator/test/schema.spec.js
packages/validator/test/schema/fixtures.js

This pull request adds schema for dictionaries (key value pairs) which are needed for defining schema for fields like
https://github.com/web3-storage/w3protocol/blob/5e6681f4886dc4e50550f58bf795944d51023f71/packages/upload-client/src/types.ts#L45

feat: implement dictionary schema

---

packages/client/test/client.spec.js
packages/core/src/delegation.js
packages/core/test/delegation.spec.js
packages/interface/src/lib.ts
packages/transport/src/car.js
packages/transport/src/jwt.js
packages/transport/test/car.spec.js
packages/transport/test/jwt.spec.js

feat: support execution of delegations

---

packages/validator/src/schema/schema.js
packages/validator/test/capability.spec.js
packages/validator/test/inference.spec.js

Motivation:
* obviate https://github.com/web3-storage/w3protocol/pull/420#discussion_r1095096263

fix: add @returns to @ucanto/validator Schema.dictionary() to avoid problematic inference when using derives

---

packages/core/src/delegation.js
packages/core/test/lib.spec.js

Previously this was outputting invalid types:
refs https://github.com/web3-storage/w3up-client/issues/57

fix: do not call exports `import` or `export`

---

.github/workflows/conventional-commits.yml

Motivation:
* I noticed [with this PR](https://github.com/web3-storage/ucanto/pull/215) that I had omitted conventional commit title and it was allowed, which I'm not used to because we use this workflow in [w3protocol](https://github.com/web3-storage/w3protocol/blob/main/.github/workflows/conventional-commits.yml) and [web3.storage](https://github.com/web3-storage/web3.storage/blob/main/.github/workflows/conventional-commits.yml)
If it doesn't make sense to use here, nbd, just close

add .github/workflows/conventional-commits.yml to check PR titles for conventional commits

---

packages/core/src/invocation.js
packages/interface/src/capability.ts
packages/server/src/api.ts
packages/server/src/handler.js
packages/server/test/server.spec.js
packages/server/test/service/store.js
packages/validator/src/capability.js
packages/validator/src/lib.js
packages/validator/src/schema/schema.js
packages/validator/src/schema/type.ts
packages/validator/test/capability-access.spec.js
packages/validator/test/capability.spec.js
packages/validator/test/delegate.spec.js
packages/validator/test/inference.spec.js
packages/validator/test/lib.spec.js
packages/validator/test/mailto.spec.js
packages/validator/test/map-schema.spec.js
packages/validator/test/util.js
packages/validator/test/voucher.js

`capability` logic came before the `Schema` did we have not got around to integrating schema fully into `capability` we even end up with bunch of code that duplicated logic that is in schema.
Consequently it became impossible to use Schema.struct or Schema.dict on the `nb` field. This PR updates `capability` to just use `Schema`.

feat!: Use schema stuff in the capabilities instead of custom parsing

---

packages/server/src/handler.js
packages/server/test/handler.spec.js

Turns out #289 did not address all of the issues, specifically it was not inferring error types properly. This attempt seems to do better

fix: provide error inference

---

packages/core/src/schema/schema.js
packages/core/test/schema.spec.js

In the IPFS Thing workshop we needed schema for bytes which I have injected into observable. This change ports it into ucanto.

feat: add Schema.bytes

---

packages/core/src/delegation.js
packages/core/src/result.js
packages/core/src/schema/schema.js
packages/core/src/schema/type.ts
packages/core/test/delegation.spec.js
packages/interface/src/lib.ts

For the workshop I have end up implementing these methods so we could archive ucan chains into bytes and extract them back. This pr adds them to the into the ucanto

feat: archive/extract api for delegations

---

packages/core/src/invocation.js
packages/interface/src/lib.ts

* Removed from unexported class.
* Added to `@ucanto/interface` so that consumers can read them.

docs: add delegation and invocation attach method comments to interface

---

packages/client/package.json
packages/principal/package.json
packages/transport/package.json
packages/validator/package.json
pnpm-lock.yaml

`@ucanto/interface` had breaking changes, but because code in dependant libraries didn't change, release-please didn't cut new releases.
by manually specifying that the `@ucanto/interface` dependency must by 8 or above, this should trigger a release-please flow to release `@ucanto/interface@8`-compatible releases of these four libs.

feat!: update `@ucanto/interface` dependencies

---

packages/server/package.json
pnpm-lock.yaml

because of the way release-please releases deps, `@ucanto/server@8.0.0` depends on `@ucanto/validator@7` which gives downstream deps nightmares
bumping these deps like this will trigger a new `@ucanto/server` release which will only depend on `ucanto@8` deps

fix: ensure `@ucanto/server` depends on v8 deps

---

packages/core/src/cbor.js
packages/core/test/cbor.spec.js

Failing on:
```js
const obj = {}
CBOR.encode({
a: obj,
b: obj
})
```

fix: cbor prepare encode wrongly identifying circular structure

---

packages/transport/src/car/response.js

Sometimes the headers are mutated by the environment the code is run in...
resolves https://github.com/web3-storage/w3up/issues/1254

fix: do not use frozen object for headers

---

packages/transport/src/http.js

Motivation:
* there are some errors in sentry that just show up as "HTTP Request Failed", even though their root causes are probably all quite distinct. Not every caller of something that might use a ucanto client is ready to catch an `HTTPError` and inspect the `.response` property to determine what happened, and in general this may be hard because the response stream can usually only be read one time and yet that's the best way to determine the error description from the service that returned a non-ok http response. So the motivation for this change is so that our other software, when this error goes uncaught, has more distinct error messages about what's going on so they 1) share more about what's going wrong and 2) therefore also get grouped by that information in error trackers like …

feat: http transport includes more information in error message when encountering non-ok http response

---

packages/transport/src/http.js

Reverts web3-storage/ucanto#340

fix: revert "feat: http transport includes more information in error message when encountering non-ok http response"

---

packages/core/src/invocation.js
packages/core/src/receipt.js
packages/core/test/invocation.spec.js
packages/interface/src/lib.ts
packages/server/test/handler.spec.js

Adds changes to support embedding effects into receipts. Behavior is similar to the way `proofs` work in the delegations. If you pass an invocation it will be embedded in a agent message, if you pass link to invocation no invocation will be embedded.

feat!: add support for embedded effects

---

packages/core/src/receipt.js
packages/core/test/receipt.spec.js
packages/interface/src/lib.ts
pnpm-lock.yaml

Adds link to receipt aligned with invocation/delegation per https://github.com/web3-storage/w3up/pull/1342#discussion_r1554187686

fix: add link to receipt

---

packages/interface/src/lib.ts
packages/server/src/error.js
packages/server/src/lib.js
packages/server/src/server.js

Updates types signatures so that static functions does not require class wrapper around server.

fix(server): loosen requirements on statics

---

packages/core/test/message.spec.js
packages/interface/src/lib.ts
packages/server/test/server.spec.js

This was previously used if passed to the constructor but not defined in types.
resolves https://github.com/storacha/ucanto/issues/359

feat: define `resolveDIDKey` server option

---

Readme.md

Copy-pasted some example code in the UCAN workshop. This fix made it work: the invocations are each individual arguments, not an array.
Wondering though if the array form would be more intuitive when batching multiple invocations - in the old docs it would be `connection.execute(invocations)`, in the working code it's `connection.execute(...invocations)`.

Fix example in README.md

---

packages/validator/src/lib.js
packages/validator/test/session.spec.js

If proofs contain an attestation that is not issued by the service authority then `claim(...)` will recurse indefinitely.

fix: infinite recursion with unknown attestation

---

packages/core/src/schema/schema.js
packages/interface/src/capability.ts
packages/interface/src/lib.ts
packages/server/src/handler.js
packages/validator/src/error.js
packages/validator/src/lib.js
packages/validator/test/session.spec.js

This PR implements #268 
Specifically, we are changing the `did:web:web3.storage` service DID to `did:web:up.storacha.network` and want to allow attestations issued by `did:web:web3.storage` to still be considered valid.
resolves #268 
closes #267

feat: validate attestation from another service

---

packages/interface/src/lib.ts
packages/server/src/handler.js
packages/server/src/server.js
packages/server/test/server.spec.js

This PR adds a new server option `audience`, which allows the server to accept invocations for audiences other than the service itself.
This option was already available (and continues to be available) on a per handler basis (via `provideAdvanced`), it takes precedence over the new global server audience.
Concretely, the DID for web3.storage is changing, but we want to be able to accept invocations targeting the old DID without having to configure every single handler.

feat: allow alternative audience for server

---

packages/core/src/schema/schema.js

Fixes issue in newer typescript versions that is not ignorable or expect-error-able:

fix: exported anonymous class type may not be private or protected

---

packages/transport/src/http.js
packages/transport/test/https.spec.js

Added the ability to set default headers when creating HTTP channels that get merged with request headers. 
Request headers take precedence over channel headers.
This will allow us to pass custom headers to track which tool the agents are running (CLI, console, etc).
See: https://github.com/storacha/ai-integrations/issues/48

feat(transport): support custom headers in HTTP transport

---

packages/server/src/server.js
packages/server/test/server.spec.js

Currently, when a request has a malformed payload, the decoder throws an exception which is caught and returned as a handler execution error. This change improves error handling by specifically catching decoder exceptions and returning a proper HTTP 400 Bad Request response with a meaningful error message, making it clearer to clients that the issue is with their request format. Closes #358

fix: Return 400 Bad Request for malformed payloads instead of handler execution error
