storacha/ucanto

Readme.md

heyo, just made a few edits here while I was reading through to get up to speed.

chore: edit readme for grammar, etc

---

src/transport/http.js
test/client.spec.js
yarn.lock

Motivation:
* I tried to use the http method, but it didn't work because it was trying to send http GET with a body, which most fetch impls block because it's not valid http

http transport supports injecting default http method, fetch impl

---

packages/principal/test/ed25519.spec.js

fix #85 until we encountered it again
P.S.: Targeting #102 to avoid even more merge conflicts

chore: test serialized ed keys with slash

---

packages/principal/package.json
packages/principal/src/ed25519/signer.js
packages/principal/src/ed25519/verifier.js
packages/validator/src/schema/link.js
packages/validator/src/schema/schema.js

fix: fixes for #108

---

packages/core/package.json
packages/transport/package.json
packages/validator/package.json
pnpm-lock.yaml

This is eradicate multiformats@9 from the tree.

fix: update @ipld/car and @ipld/dag-cbor deps

---

packages/validator/test/lib.spec.js

I can not believe this test was missing, but [following discussion](https://github.com/web3-storage/w3protocol/pull/148/files#r1024259741) led me to believe there was a bug in the validator.
I'm glad to report that principal misalignment creates authorization error and explain what's wrong

chore: add missing principal aligment test

---

.vscode/settings.json
packages/core/package.json
packages/interface/package.json
packages/interface/src/lib.ts
packages/principal/package.json
packages/principal/src/ed25519/signer.js
packages/principal/src/ed25519/type.ts
packages/principal/src/ed25519/verifier.js
packages/principal/src/rsa.js
packages/principal/src/rsa/type.ts
packages/principal/src/verifier.js
pnpm-lock.yaml

This is another attempt to land #156

feat: update to latest dag-ucan

---

packages/validator/src/error.js
packages/validator/src/lib.js
packages/validator/test/error.spec.js
packages/validator/test/lib.spec.js

Fixes #184 per troubles we've experienced today with mismatched keys

fix: error messages on invalid proofs

---

packages/validator/src/schema/did.js
packages/validator/test/extra-schema.spec.js

Motivation:
* https://github.com/web3-storage/ucanto/issues/175

Add @ucanto/validator DID.from

---

package.json
packages/client/package.json
packages/core/package.json
packages/interface/package.json
packages/principal/package.json
packages/server/package.json
packages/transport/package.json
packages/validator/package.json
pnpm-lock.yaml

Update to multiformats 11.
P.S.: @hugomrdias I have not encountered any of the issues we observed on your machine, so I suspect it's was something with your local changes or a setup.

chore: update multiformats

---

Readme.md

Let's come back to this after w3up release, but these are some places the README could use cleanup.

readme updates

---

pnpm-lock.yaml

Motivation:
* fix https://github.com/web3-storage/ucanto/actions/runs/4139781505/jobs/7157755857#step:5:30

pnpm install to fix pnpm-lock.yaml

---

.github/release-please-config.json

https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md?plain=1#L146
>   //   - never ignored: remove/change it once a good release PR is merged

rm release-please-config last-release-sha

---

.github/release-please-config.json
.github/release-please-manifest.json
.github/workflows/release.yml
packages/client/package.json
packages/core/package.json
packages/principal/package.json
packages/server/package.json
packages/transport/package.json
packages/validator/package.json
pnpm-lock.yaml

Attempts to reconfigure release-please similar to https://github.com/web3-storage/w3protocol/blob/main/.github/workflows/release.yml in a hope to address release issues

fix: reconfigure release-please

---

package.json
packages/client/package.json
packages/core/package.json
packages/interface/package.json
packages/principal/package.json
packages/server/package.json
packages/transport/package.json
packages/transport/src/car.js
packages/transport/src/car/codec.js
packages/validator/package.json
pnpm-lock.yaml

feat: implement sync car decode

---

packages/interface/src/capability.ts
packages/server/src/handler.js
packages/server/src/server.js
packages/server/test/handler.spec.js
packages/validator/src/error.js
packages/validator/src/lib.js
packages/validator/test/error.spec.js

feat: configurable audience handlers

---

packages/transport/src/car/codec.js

fix: car imports

---

packages/transport/package.json

Identified issue was breaking skypack builds

fix: type exports

---

packages/server/src/handler.js
packages/server/test/handler.spec.js

Improves inference of the `.provide` function that

fix: inference of provide function

---

packages/transport/src/legacy.js

Need to use it in https://github.com/web3-storage/w3up/pull/767/files

fix: export legacy request/response

---

packages/client/package.json
packages/principal/package.json
packages/transport/package.json
packages/validator/package.json
pnpm-lock.yaml

per https://github.com/web3-storage/ucanto/pull/310#issuecomment-1557963060

chore: move back to ^ interface deps

---

.npmrc
packages/client/test/client.spec.js
packages/server/package.json
packages/server/test/server.spec.js
pnpm-lock.yaml

fix: add missing dependency on `@ucanto/principal`

---

packages/server/package.json
pnpm-lock.yaml

I think this fixes leftover from #312

fix: dependency versions

---

packages/validator/src/lib.js
packages/validator/test/session.spec.js

This fixes the problem caused by the attestation validator

fix: exponential scan

---

packages/client/src/connection.js
packages/principal/src/lib.js
packages/transport/src/lib.js
packages/validator/src/lib.js

Interface for other packages is outdated and is causing type issues, so we need to bump them as patch for new installs

fix: trigger interface upgrade for all packages

---

packages/client/README.md
packages/core/README.md
packages/interface/README.md
packages/principal/README.md
packages/server/README.md
packages/transport/README.md
packages/validator/README.md

This PR adresses issue #219 adds detailed README.md files to all ucanto sub-packages to improve documentation and help users understand the purpose and usage of each package.

docs: added readmes to sub-packages
